In [2]:
#import libraries
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
#import dataset
energy=pd.read_csv(r"C:\Users\HARI\Downloads\energy_efficiency.csv")
energy

Surface_Area  Wall_Area  Roof_Area  Overall_Height  Heating_Load  \
0           514.5      294.0     110.25             7.0         15.55   
1           514.5      294.0     110.25             7.0         15.55   
2           514.5      294.0     110.25             7.0         15.55   
3           514.5      294.0     110.25             7.0         15.55   
4           563.5      318.5     122.50             7.0         20.84   
..            ...        ...        ...             ...           ...   
763         784.0      343.0     220.50             3.5         17.88   
764         808.5      367.5     220.50             3.5         16.54   
765         808.5      367.5     220.50             3.5         16.44   
766         808.5      367.5     220.50             3.5         16.48   
767         808.5      367.5     220.50             3.5         16.64   

     Cooling_Load  
0           21.33  
1           21.33  
2           21.33  
3           21.33  
4           28.28  
..            ...  
763         21.40  
764         16.88  
765         17.11  
766         16.61  
767         16.03  

[768 rows x 6 columns]

In [6]:
energy.head(10)

Surface_Area  Wall_Area  Roof_Area  Overall_Height  Heating_Load  \
0         514.5      294.0     110.25             7.0         15.55   
1         514.5      294.0     110.25             7.0         15.55   
2         514.5      294.0     110.25             7.0         15.55   
3         514.5      294.0     110.25             7.0         15.55   
4         563.5      318.5     122.50             7.0         20.84   
5         563.5      318.5     122.50             7.0         21.46   
6         563.5      318.5     122.50             7.0         20.71   
7         563.5      318.5     122.50             7.0         19.68   
8         588.0      294.0     147.00             7.0         19.50   
9         588.0      294.0     147.00             7.0         19.95   

   Cooling_Load  
0         21.33  
1         21.33  
2         21.33  
3         21.33  
4         28.28  
5         25.38  
6         25.16  
7         29.60  
8         27.30  
9         21.97

In [352]:

X=pd.DataFrame(chennai.iloc[:,[1]]).values


In [353]:
X.shape

(768, 1)

In [354]:
y=pd.DataFrame(energy.iloc[:,5]).values////////

In [355]:
y.shape


(768, 1)

In [356]:
rgr=LinearRegression()


In [357]:
model=rgr.fit(X,y)

In [358]:
model.coef_

array([[0.09313826]])

In [359]:
model.coef_*1000

array([[93.13825859]])

In [360]:
model.intercept_ # b0 - constant / yintercept
print((model.intercept_)*1000)

[-5076.77494518]


In [373]:
model.predict(X)[100]*1000 # machine predicted output - y hat

array([24587.76041667])

In [374]:
energy.Cooling_Load[100]*1000 # actual output/ original output - y

32540.0

In [375]:
model.score(X,y)

0.18242892969618607

In [376]:
print(100-18.2,'%')

81.8 %
