In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\HARI\Downloads\ml_projects\Website Phishing.csv")
df

SFH  popUpWidnow  SSLfinal_State  Request_URL  URL_of_Anchor  \
0       1           -1               1           -1             -1   
1      -1           -1              -1           -1             -1   
2       1           -1               0            0             -1   
3       1            0               1           -1             -1   
4      -1           -1               1           -1              0   
...   ...          ...             ...          ...            ...   
1348   -1           -1              -1           -1             -1   
1349   -1            0               1            0             -1   
1350   -1            0              -1           -1             -1   
1351    0            0               1            0              0   
1352    1            0               1            1              1   

      web_traffic  URL_Length  age_of_domain  having_IP_Address  Result  
0               1           1              1                  0       0  
1               0           1              1                  1       1  
2               0          -1              1                  0       1  
3               0           1              1                  0       0  
4               0          -1              1                  0       1  
...           ...         ...            ...                ...     ...  
1348           -1           0              1                  0       1  
1349            0           0              1                  0      -1  
1350            0          -1             -1                  0       1  
1351            0          -1              1                  0       1  
1352            0          -1             -1                  0      -1  

[1353 rows x 10 columns]

In [3]:
X=df.drop('Result',axis=1).values 
y=df['Result'].values

In [4]:
# transform the labels to 0's , 1's and -1's
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
y = enc.fit_transform(y)

for i in range(0, len(X)):
    X[i] = enc.fit_transform(X[i])

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=10)

# Show the results of the split
print("Training set has {} samples.".format(X_train.shape[0]))
print("Testing set has {} samples.".format(X_test.shape[0]))

Training set has 947 samples.
Testing set has 406 samples.


In [6]:
from sklearn.naive_bayes import MultinomialNB

#create Naive Bayes object
model=MultinomialNB(alpha=1.0)

#Train the model using training data 
model.fit(X_train,y_train)

MultinomialNB()

In [7]:
from sklearn.metrics import accuracy_score
#Test the model using testing data
predictions = model.predict(X_test)

In [8]:

print("The accuracy of your Naive bayes on testing data is: ",100.0 *accuracy_score(y_test,predictions))


The accuracy of your Naive bayes on testing data is:  78.81773399014779


In [9]:
from sklearn.metrics import confusion_matrix,classification_report

In [10]:
print('confusion matrix output is\n',confusion_matrix(y_test,predictions))

confusion matrix output is
 [[190   0  18]
 [ 16   3  14]
 [ 38   0 127]]


In [11]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.78      0.91      0.84       208
           1       1.00      0.09      0.17        33
           2       0.80      0.77      0.78       165

    accuracy                           0.79       406
   macro avg       0.86      0.59      0.60       406
weighted avg       0.80      0.79      0.76       406

